database:
  driverClass: org.postgresql.Driver
  user: authdb
  password: authdb
  url: jdbc:postgresql://localhost/authdb
  minSize: 1

server:
  type: simple
  applicationContextPath: /auth/
  adminContextPath: /admin
  connector:
    type: http
    port: 9073
  requestLog:
    appenders: []    
  gzip:
    bufferSize: 8KiB

assets:
 overrides:
   /admin: web_ui/src/main/webapp/app/

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO    
    org.hibernate.SQL: INFO
    com.sun.jersey.api.container.filter.LoggingFilter: WARN
  appenders:
    - type: console

refdata: refdata

modelResource: auth-model.xml
   
beanValidationConstraints: constraints.xml

shiro:
  enabled: true
  session_handler: true
  url_pattern: /*

swagger:
  resourcePackage: com.thesett.auth.services

clientSecrets:
  github: 65581bc5b464b75fcca0e236e9831b5a1ad6eb3d
  google: XffE21yn1JZllanUpE1t-diy
  facebook: 83925f504c5fbddcae6d944848f878ab

infinispan:
  bindAddress: 127.0.0.1
  initialHosts: localhost[7800],localhost[7801]
  clusterName: auth-cluster
  type: clustered

apis:
  root: "/api/"